title: Grocery Store Analytics
email: contact@robertakarobin.com
baseurl: ""

sass:
  sass_dir: assets/sass
  style: expanded

kramdown:
  auto_ids: false

collections:
  products:
    output: true
    sort_by: name
